language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - make develop
script:
  - make test
after_success:
  - pip install -q --use-mirrors python-coveralls
  - coveralls
